
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
           <!DOCTYPE html>     
            <html lang="en">
            <head
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">  
                <title>TECHMAZE | Course login </title>
                <style>*{      >  margin: 0;
                  padding: 0;
              }
              .main{
                  width: 100%;
                  background: linear-gradient(to top, rgba(0,0,0,0.5)50%, rgba(0,0,0,0.5)50%), url(retina_1708x683_image6-5a83060bece4d310324634c1e39452c2.png);
                  background-position: center;
                  background-size: cover;
                  height: 100vh;
              }
              .navbar{
                  width: 1200px;
                  height: 75px;
                  margin: auto;
              }
              .icon{
                  width: 200px;
                  float: left;
                  height: 70px;
              }
          
              .logo{
                  color: #ff7200;
                  font-size: 35px;
                  font-family: Arial;
                  padding-left: 20px;
                  float: left;
                  padding-top: 10px;
                  margin-top: 5px;
              }
              .menu{
                  width: 400px;
                  float: left;
                  height: 70px;
              }
              ul{
                  float: left;
                  display: flex;
                  justify-content: center;
                  align-items: center;
              }
              ul li {
                 list-style: none;
                 margin-left: 62px;
                 margin-top: 27px;
                 font-size: 14px;
              }
              ul li a{
                  text-decoration: none;
                  color: #fff;
                  font-family: Arial;
                  font-weight: bold;
                  transition: 0.4s ease-in-out;
              }
              ul li a:hover {
                  color: #ff7200;
              }
              .search{
                  width: 330px;
                  float: left;
                  margin-left: 270px;
              }
          
              .srch{
                  font-family: 'Times New Roman';
                  width: 200px;
                  height: 40px;
                  background: transparent;
                  border: 1px solid #ff7200;
                  margin-top: 13px;
                  color: #fff;
                  border-right: none;
                  font-size: 16px;
                  float: left;
                  padding: 10px;
                  border-bottom-left-radius: 5px;
                  border-top-left-radius: 5px;
              }
          
              .btn{
                  width: 120px;
                  height: 40px;
                  background: #ff7200;
                  border: 2px solid #ff7200;
                  margin-top: 13px;
                  color: #fff;
                  font-size: 15px;
                  border-bottom-right-radius: 5px;
                  border-bottom-right-radius: 5px;
                  transition: 0.2s ease;
                  cursor: pointer;
              }
              .btn:hover{
                  color: #000;
              }
          
              .btn:focus{
                  outline: none;
              }
          
              .srch:focus{
                  outline: none;
              }
              .content{
                  width: 1200px;
                  height:auto;
                  margin: auto;
                  color: #fff;
                  position: relative;
              }
              .content .par{
                  padding-left: 20px;
                  padding-bottom: 25px;
                  font-family: Arial;
                  letter-spacing: 1.2px;
                  line-height: 30px;
              }
              .content h1 {
                  font-family: 'Times New Roman';
                  font-size: 50px;
                  padding-left: 20px;
                  margin-top: 9%;
                  letter-spacing: 2px;
              }
              .content .cn {
                  width: 160px;
                  height: 40px;
                  background: #ff7200;
                  border: none;
                  margin-bottom: 10px;
                  margin-left: 20px;
                  font-size: 18px;
                  border-radius: 10px;
                  cursor: pointer;
                  transition: .4s ease;
              }
          
              .content .cn a {
                  text-decoration: none;
                  color: #000;
                  transition: .3s ease;
              }
          
              .cn:hover{
                  background-color: #fff;
              }
              .content span{
                  color: #ff7200;
                  font-size: 65px;
              }
              .form {
                  width: 250px;
                  height: 380px;
                  background: linear-gradient(to top, rgba(0,0,0,0.8)50%, rgba(0,0,0,0.8)50%);
                  position: absolute;
                  top: -20px;
                  left: 870px;
                  transform: translate(0%, -5%);
                  border-radius: 10px;
                  padding: 25px;
          
              }
          
              .form h2 {
                  width: 220px;
                  font-family: sans-serif;
                  text-align: center;
                  color: #ff7200;
                  background-color: #fff;
                  border-radius: 10px;
                  margin: 2px;
                  padding: 8px;
              }
          
              .form input{
                  width: 240px;
                  height: 35px;
                  background: transparent;
                  border-bottom: 1px solid #ff7200;
                  border-top: none;
                  border-right: none;
                  border-left: none;
                  color: #fff;
                  font-size: 15px;
                  letter-spacing: 1px;
                  margin-top: 30px;
                  font-family: sans-serif;
              }
          
              .form input:focus{
                  outline: none;
              }
          
              ::placeholder{
                  color: #fff;
                  font-family: Arial;
              }
              .btnn{
                  width: 240px;
                  height: 40px;
                  background: #ff7200;
                  border: none;
                  margin-top: 30px;
                  font-size: 18px;
                  cursor: pointer;
                  color: #fff;
                  transition: 0.4s ease;
              }
          
              .btnn:hover{
                  text-decoration: none;
                  color: #000;
                  font-weight: bold;
              }
              .btnn a{
                  text-decoration: none;
                  color: #000;
                  font-weight: bold;
              }
          
              .form .link{
                  font-family: Arial, Helvetica, sans-serif;
                  font-size: 17px;
                  padding-top: 20px;
                  text-align: center;
              }
          
              .form .link a{
                  text-decoration: none;
                  color: #ff7200;
              }
              .liw{
                  padding-top: 15px;
                  padding-bottom: 10px;
                  text-align: center;
              }
              .icons a {
                  text-decoration: none;
                  color: #fff;
              }
              .icons ion-icon{
                  color: #fff;
                  font-size: 30px;
                  padding-left: 14px;
                  padding-top: 5px;
                  transition: 0.3s ease;
              }
          
              .icons ion-icon:hover {
                  color: #ff7200;
              }
              </style>
          </head>
          <body>
              <div class="main">
                  <div class="navbar">
                      <div class="icon">
                          <h2 class="logo">TECHMAZE</h2>
                      </div>
              
                      <div class="menu">
                          <ul>
                              <li><a href="#">HOME</a></li>
                              <li><a href="#">ABOUT</a></li>
                              <li><a href="#">SERVICE</a></li>
                              <li><a href="#">DESIGN</a></li>
                              <li><a href="#">CONTACT</a></li>
                          </ul>
                      </div>
              
                      <div class="search">
                          <input class="srch" type="search" name="" placeholder="Type To text">
                          <a href="#"> <button class="btn">Search</button></a>
                      </div>
              
                  </div> 
                  <div class="content">
                      <h1>Python  <br><span>TECHMAZE</span> <br>Course</h1>
                      <p class="par">Welcome to our website TECHMAZE.
                          <br> I hope you like the different learning experience that was created on the site.
                           <br>The goal of this site is to let all of Egypt know what software is and how to deal with it in this time
                           <br>and what its functions are and how we program and learn programming languages.
                           <br>There will be a reliable certificate from the site that will prove that you are
                            <br>Understand the software after you finish, but there are some tests
                            <br>that we will take before you enter any course in order to determine your level
                            <br> </p>
                          
                           
                          <button onclick="document.location= 'https://www.programiz.com/python-programming/online-compiler/'" class="cn"><a href="#">Code Python</a></button>
                           
          
                          <div class="form">
                              <h2>Login Here</h2>
                              <input type="email" name="email" placeholder="Enter Email Here">
                              <input type="password" name="" placeholder="Enter Password Here">
                              <button onclick="document.location= 'https://sites.google.com/view/techmaze-1/home'" class="btnn"><a href="#">Login</a></button>
          
                              <p class="link">Don't have an account<br>
                              <a href="#">Sign up </a> here</a></p>
                              <p class="liw">Log in with</p>
              
                              <div class="icons">
                                  <a href="#"><ion-icon name="logo-facebook"></ion-icon></a>
                                  <a href="#"><ion-icon name="logo-instagram"></ion-icon></a>
                                  <a href="#"><ion-icon name="logo-twitter"></ion-icon></a>
                                  <a href="#"><ion-icon name="logo-google"></ion-icon></a>
                                  <a href="#"><ion-icon name="logo-skype"></ion-icon></a>
                              </div>
              
                          </div>
                              </div>
                          </div>
                  </div>
              </div>
              <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
          </body>
          </html>
